#!/bin/bash

set -e
set -o pipefail

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
	echo "usage: $0 [LIST-OF-LISTS-URL]" 1>&2
	exit 1
fi

LIST_OF_LISTS_URL=${1:-"https://v.firebog.net/hosts/lists.php?type=tick"}

download_list() {
	for i in $(wget -q -O - "$LIST_OF_LISTS_URL") ; do wget -q -O - "$i" ; echo ; done
}

convert_to_unix_lf() {
	sed -E 's/\r$//'
}

remove_leading_ips() {
	sed -E 's/^0\.0\.0\.0[[:space:]]*//' | sed -E 's/127\.0\.0\.1[[:space:]]+//'
}

remove_comments() {
	sed -E 's/[[:space:]]*#.+$//'
}

lowercase() {
	tr '[:upper:]' '[:lower:]'
}

remove_empty_lines() {
	grep -Ev '^[[:space:]]*$'
}

replace_matcher_components() {
	sed -E 's/^\|\|([a-z0-9.-]+)\^$/\1/' | tee debug.txt
}

remove_invalid_hostnames() {
	grep -P '^[0-9\x61-\x7A\x2E\x2D]+$'
}

remove_trailing_dots() {
	sed 's/\.$//'
}

remove_pure_toplevel_domains() {
	grep -F '.' 
}

remove_pure_ips() {
	grep -Ev '^([0-9]+\.){3}([0-9]+)$' 
}

use_first_entry_if_multiple_fields() {
	sed -E 's/[[:space:]]+.+//'
}

sort_unique_by_domain_level() {
	rev | sort -u | rev
}

remove_subdomains_if_higher_level_is_already_blocked() {
	awk '{ idx = index($0, "." last); if(!(idx > 0 && idx == length($0) - length(last))) { last = $0; print $0 } }'
}

output_rpz() {
	cat <<EOF
\$ORIGIN adblock.
\$TTL 1h
@                  IN  SOA       localhost. root.localhost. (
				 $(date +%s)  ; serial
				 6h          ; refresh
                                 1h          ; retry
                                 1w          ; expire
                                 1d )        ; minimum TTL

                   IN  NS        localhost.

EOF
	while read hostname
	do
		echo "${hostname} CNAME ."
		if [ "${#hostname}" -le 243 ] # i expected 253-2, but testing proved me wrong (maybe some rpz-overhead?)
		then
			echo "*.${hostname} CNAME ."
		fi
	done
}

download_list | convert_to_unix_lf | remove_comments | remove_empty_lines | lowercase | \
	remove_leading_ips | replace_matcher_components | remove_invalid_hostnames | \
	remove_trailing_dots | remove_pure_toplevel_domains | remove_pure_ips | \
	use_first_entry_if_multiple_fields | sort_unique_by_domain_level | \
	remove_subdomains_if_higher_level_is_already_blocked | \
	output_rpz
